create table configuration (id bigint generated by default as identity (start with 1), metric_name varchar(255), metrics integer, project varchar(255), scale_down bigint, scale_up bigint, service varchar(255), primary key (id))
alter table configuration add constraint Domain-Key unique (project, service, metric_name)
