server:
  port: 8091
spring:
  application:
    name: MetricsInterpreter
  profiles:
    active: ${STAGE:local}
  rabbitmq:
          host: ${rabbitmq:localhost}
          port: 5672
          username: guest
          password: guest
  data:
    rest:
      base-path: /api/autoscaler/
  jpa:
    hibernate:
      ddl-auto: validate
    #properties:
    #  javax:
    #    persistence:
    #      schema-generation:
    #        create-source: metadata
    #        scripts:
    #          action: create
    #          create-target: create.sql
flyway:
  baseline-on-migrate:  true