server:
  port: 8091
spring:
  application:
    name: Scaler
  profiles:
    active: ${STAGE:local}
  rabbitmq:
          host: ${rabbitmq:localhost}
          port: 5672
          username: guest
          password: guest
  data:
    rest:
      base-path: /api/autoscaler/
  jpa:
    hibernate:
      ddl-auto: update