server:
  port: 8092
spring:
  application:
    name: MetricsStats
  profiles:
    active: ${STAGE:local}
autoscale-scaler:
  url: http://autoscale-scaler:8090
autoscale-interpreter:
  url: http://autoscale-interpreter:8091