CREATE TABLE autoscale_configuration
(
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project     CHARACTER VARYING(255) NOT NULL,
  service     CHARACTER VARYING(255) NOT NULL,
  metric_name CHARACTER VARYING(255) NOT NULL,
  metrics     CHARACTER VARYING(255) NOT NULL,
  scale_up    BIGINT                 NOT NULL,
  scale_down  BIGINT                 NOT NULL,
  CONSTRAINT autoscale_configuration_domainkey UNIQUE (project, service, metrics, metric_name)
);

CREATE TABLE service_limit
(
  id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project  CHARACTER VARYING(255) NOT NULL,
  service  CHARACTER VARYING(255) NOT NULL,
  min_pods BIGINT                 NOT NULL,
  max_pods BIGINT                 NOT NULL,
  CONSTRAINT servicelimit_domainkey UNIQUE (project, service)
);